version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - syslog
        container_name: flask

    syslog:
        image: rsyslog/syslog_appliance_alpine
        container_name: rsyslog
